# Generated by Django 5.0.3 on 2024-03-14 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureGate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(help_text='Enter a description for the application.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(help_text='Enter the name of the application.', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.URLField(help_text='Enter the URL of the application.'),
        ),
        migrations.AlterField(
            model_name='function',
            name='application',
            field=models.ForeignKey(help_text='Select the application this function belongs to.', on_delete=django.db.models.deletion.CASCADE, to='SecureGate.application'),
        ),
        migrations.AlterField(
            model_name='function',
            name='description',
            field=models.TextField(help_text='Enter a description for the function.'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(help_text='Enter the name of the function.', max_length=100),
        ),
        migrations.AlterField(
            model_name='functionaccess',
            name='function',
            field=models.ForeignKey(help_text='Select the function.', on_delete=django.db.models.deletion.CASCADE, to='SecureGate.function'),
        ),
        migrations.AlterField(
            model_name='functionaccess',
            name='user',
            field=models.ForeignKey(help_text='Select the user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='application',
            field=models.ForeignKey(help_text='Select the application.', on_delete=django.db.models.deletion.CASCADE, to='SecureGate.application'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='functions',
            field=models.ManyToManyField(blank=True, help_text='Select the functions this user can access.', to='SecureGate.function'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='user',
            field=models.ForeignKey(help_text='Select the user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
