# Generated by Django 5.0.3 on 2024-03-18 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureGate', '0002_alter_application_description_alter_application_name_and_more'),
        ('TicketManager', '0003_ticket_assignee_ticket_task_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username of the user.', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the user.', max_length=254)),
                ('salt', models.CharField(editable=False, help_text='Salt to be used for signing tokens.', max_length=50)),
                ('signed_token', models.CharField(help_text='Signed token for password reset link.', max_length=200)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the password reset request.')),
                ('password_change_date', models.DateTimeField(blank=True, help_text='Date and time when the password was changed after the reset request.', null=True)),
                ('ticket', models.ForeignKey(help_text='Reference to the ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to='TicketManager.ticket')),
            ],
        ),
    ]
