# Generated by Django 5.0.3 on 2024-03-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureGate', '0003_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='salt',
            field=models.CharField(blank=True, help_text='Salt to be used for signing tokens.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='signed_token',
            field=models.CharField(blank=True, help_text='Signed token for password reset link.', max_length=200, null=True),
        ),
    ]
