# Generated by Django 5.0.3 on 2024-03-19 08:47

import SecureGate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureGate', '0004_alter_passwordresetrequest_salt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='salt',
            field=models.CharField(default=SecureGate.models.generate_salt, help_text='Salt to be used for signing tokens.', max_length=50),
        ),
    ]
