# Generated by Django 5.0.3 on 2024-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureGate', '0006_alter_passwordresetrequest_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='url',
            field=models.CharField(blank=True, help_text='Password reset link.', max_length=100, null=True),
        ),
    ]
