# Generated by Django 5.0.3 on 2024-05-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureGate', '0007_passwordresetrequest_url'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='access_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='auth.group'),
        ),
        migrations.AddField(
            model_name='application',
            name='display_name',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
