# Generated by Django 5.0.3 on 2024-03-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='created_at',
            new_name='open_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_reference',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=20),
        ),
    ]
