# Generated by Django 4.2.7 on 2026-02-25 18:26

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeastRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(default='/opt/feast/feature_repo', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('default_owner', models.CharField(default='Data Platform Team', max_length=255)),
                ('architecture_json', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Complete diagram state including nodes, edges, positions')),
                ('settings', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('json_hash', models.CharField(blank=True, help_text='MD5 hash of last saved JSON', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('context_json', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Snapshot of repository state when chat started')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_sessions', to='FeastArchitect.feastrepository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('query_type', models.CharField(blank=True, help_text='generate_code, optimize, etc.', max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='FeastArchitect.llmchatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_name', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('join_key', models.CharField(default='id', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('pos_x', models.FloatField(default=100)),
                ('pos_y', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='FeastArchitect.feastrepository')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('repository', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('sqlite', 'SQLite'), ('mongodb', 'MongoDB'), ('dynamodb', 'DynamoDB'), ('cassandra', 'Cassandra'), ('couchbase', 'Couchbase'), ('elasticsearch', 'Elasticsearch'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery'), ('redshift', 'Redshift'), ('databricks', 'Databricks Delta Lake'), ('synapse', 'Azure Synapse'), ('kafka', 'Apache Kafka'), ('kinesis', 'AWS Kinesis'), ('pulsar', 'Apache Pulsar'), ('eventhubs', 'Azure Event Hubs'), ('s3', 'Amazon S3 (Parquet)'), ('gcs', 'Google Cloud Storage'), ('azureblob', 'Azure Blob Storage'), ('minio', 'MinIO'), ('redis', 'Redis'), ('memcached', 'Memcached'), ('dragonfly', 'Dragonfly'), ('neo4j', 'Neo4j'), ('neptune', 'Amazon Neptune'), ('influxdb', 'InfluxDB'), ('timescaledb', 'TimescaleDB'), ('clickhouse', 'ClickHouse'), ('couchdb', 'CouchDB'), ('rethinkdb', 'RethinkDB'), ('firebase', 'Firebase'), ('supabase', 'Supabase')], max_length=50)),
                ('owned_by', models.CharField(default='Data Platform Team', max_length=255)),
                ('access_process', models.TextField(blank=True, help_text='Steps to get access')),
                ('connection_string', models.CharField(blank=True, max_length=500)),
                ('topic', models.CharField(blank=True, help_text='For Kafka sources', max_length=255)),
                ('feast_connection_type', models.CharField(choices=[('batch', 'Batch (FileSource)'), ('stream', 'Stream (KafkaSource)'), ('push', 'Push (PushSource)'), ('request', 'Request Source')], default='batch', help_text='How this source connects to Feast', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('pos_x', models.FloatField(default=100)),
                ('pos_y', models.FloatField(default=100)),
                ('column_security', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='PII columns, masked columns, restricted columns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='FeastArchitect.feastrepository')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('repository', 'name')},
            },
        ),
    ]
